# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 00:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
